CREATE TABLE TBL_ARTIST_201905(
    ARTIST_ID CHAR(4) NOT NULL PRIMARY KEY,
    ARTISE_NAME VARCHAR2(20),
    ARTIST_BIRTH CHAR(8),
    ARTIST_GENDER CHAR(1),
    TALENT CHAR(1),
    AGENCY VARCHAR(30)
);
CREATE TABLE TBL_MENTO_201905(
    MENTO_ID CHAR(4) NOT NULL PRIMARY KEY,
    MENTO_NAME VARCHAR2(20)
);
CREATE TABLE TBL_POINT_201905(
    SERIAL_NO NUMBER(8) NOT NULL PRIMARY KEY,
    ARTIST_ID CHAR(4),
    MENTO_ID CHAR(4),
    POINT NUMBER(3)
);